deCREATE DATABASE DBLAB;


CREATE TABLE BITACORA(
IDBITACORA int identity(1,1) primary key,
fecha date, 
descripcion varchar(255),
tipo varchar(20)
);


CREATE TABLE USUARIO(
idusuario int identity(1,1) primary key,
nombres varchar(255),
usuario varchar(45),
password varchar(45),
estado varchar(2),
IDBITACORA INT,
FOREIGN KEY(IDBITACORA) REFERENCES BITACORA(IDBITACORA)
);

CREATE TABLE FORMULARIO(
idformulario int identity(1,1) primary key,
nombre varchar(45),
descripcion varchar(255)
);

CREATE TABLE USUARIO_HAS_FORMULARIO(
IDUSUARIO INT,
IDFORMULARIO INT,
FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
FOREIGN KEY(IDFORMULARIO) REFERENCES FORMULARIO(IDFORMULARIO)
);


CREATE TABLE BACKUP_REG(
IDBACKUP INT IDENTITY(1,1) PRIMARY KEY,
FECHA DATE,
UBICACION VARCHAR(255),
ESTADO VARCHAR(2)
);


CREATE TABLE MUESTRA(
IDMUESTRA INT IDENTITY(1,1) PRIMARY KEY,
DESCRIPCION VARCHAR(125)
);




CREATE TABLE PACIENTE(
IDPACIENTE INT IDENTITY(1,1) PRIMARY KEY,
NOMBRES VARCHAR(155),
APELLIDOS VARCHAR(150),
FECHA_NACIMIENTO DATE,
TELEFONO VARCHAR(10),
DIRECCION VARCHAR(255)
);


CREATE TABLE ANALISIS(
IDANALISIS INT IDENTITY(1,1) PRIMARY KEY,
FECHA DATE,
ESTADO VARCHAR(2),
IDPACIENTE INT,
IDMUESTRA INT,
FOREIGN KEY(IDPACIENTE) REFERENCES PACIENTE(IDPACIENTE),
FOREIGN KEY(IDMUESTRA) REFERENCES MUESTRA(IDMUESTRA)
);


CREATE TABLE TIPO_ANALISIS(
IDTIPOANALISIS INT IDENTITY(1,1) PRIMARY KEY,
DESCRIPCION VARCHAR(255),
IDMUESTRA INT,
FOREIGN KEY(IDMUESTRA) REFERENCES MUESTRA(IDMUESTRA)
);



 -- Pendiente estas tablas 
CREATE TABLE RESULTADO(
IDRESULTADO INT IDENTITY(1,1) PRIMARY KEY,
FECHA DATE,
DESCRIPCION VARCHAR(45),
);

CREATE TABLE ANALISIS_HAS_TIPO_ANALISIS(
IDANALISIS INT,
IDTIPOANALISIS INT,
FOREIGN KEY(IDANALISIS) REFERENCES ANALISIS(IDANALISIS),
FOREIGN KEY(IDTIPOANALISIS) REFERENCES TIPO_ANALISIS(IDTIPOANALISIS)
);